### ISSUE TITLE
PRs get ignored in the changelog for no apparent reason

### ISSUE THREAD

**Issue by ccremer** [mikepenz/release-changelog-builder-action#154] opened 2021-01-11 17:06 UTC
Hi

I'm not sure if it's an issue with the action itself or whether we use it incorrectly.

Preconditions:
1. We are using v1.3.1 of this action. It's maybe notable that there was a version upgrade from 1.2.3 to 1.3.1 between rc2 and rc3
2. We use the new feature `outputFile` in [config](https://github.com/vshn/k8up/blob/master/.github/workflows/release.yml#L40)
3. We use a [custom config](https://github.com/vshn/k8up/blob/master/.github/changelog-configuration.json)

New release:
1. We have released a new prerelease: [v1.0.0-rc3](https://github.com/vshn/k8up/releases/tag/v1.0.0-rc3)
2. It shows the changelog, but some PRs are missing, compared to [v1.0.0-rc2](https://github.com/vshn/k8up/releases/tag/v1.0.0-rc2). I understand the `ignorePrereleases` setting as if previous releases wouldn't exist, so it builds the changelog from the last "stable" release. Examples:
  - https://github.com/vshn/k8up/pull/202 is in rc2, but not rc3, Labels are correct
  - https://github.com/vshn/k8up/pull/218 is in rc2, but not rc3. Labels are correct
  - There are more ignored PRs, haven't listed more though.
  - This is the [GH run for rc2](https://github.com/vshn/k8up/runs/1626651928)
  - This is the [GH run for rc3](https://github.com/vshn/k8up/runs/1682512372)

Logs
```
📘 Reading input values
  🔖 Resolved current tag (v1.0.0-rc3) from the 'github.context.ref'
🔖 Resolve previous tag
  ℹ️ Found 24 (fetching max: 200) tags from the GitHub API for vshn/k8up
  ℹ️ Enabled 'ignorePreReleases', searching for the closest release
🚀 Load pull requests
  ℹ️ Comparing vshn/k8up - 'v0.1.10...v1.0.0-rc3'
  ℹ️ Found 250 commits from the GitHub API for vshn/k8up
  ⚠️ Adjusted 'fromDate' to go max 90 back
  ℹ️ Fetching PRs between dates 2020-10-13T16:24:24.000Z to 2021-01-11T16:24:24.000Z for vshn/k8up
  ℹ️ Retrieved 57 merged PRs for vshn/k8up
  ℹ️ Retrieved 250 release commits for vshn/k8up
📦 Build changelog
  ℹ️ Sorted all pull requests ascending: ASC
  ℹ️ Used 1 transformers to adjust message
  ✒️ Wrote messages for 57 pull requests
  ℹ️ Ordered all pull requests into 6 categories
  ✒️ Wrote 57 categorized pull requests down
  ✒️ Wrote 0 non categorized pull requests down
  ✒️ Wrote 0 ignored pull requests down
  ℹ️ Filled template
```
Also interesting is this `250 commits`. Is this just by coincidence or some internal limit? If it's a limit, it's not based on the history, since those missing PRs are seemingly random in the history (so no "filtered out oldest PRs"). The mentioned PRs also fit into the "90 days back" window.

Do you have an answer? Or is my expectation wrong?

**Comment by ccremer** [comment] 2021-01-11 17:16
Just compared the 2 runs side by side. How can it go from 99 merged PRs for rc2 down to 57 rc3?
- My search: https://github.com/vshn/k8up/pulls?page=4&q=is%3Apr+is%3Amerged
- There were no PRs merged between 2020-10-01 and 2020-10-13 (date of merge) that would explain that much difference regarding 90 day window

**Comment by mikepenz** [comment] 2021-01-11 17:52
@ccremer having a look at this now. 

The action will retrieve all pull requests merged between 2 tags, it will stop at 200 pull requests though to not cause issues if unanticipated values are used. (you can modify this in the config)
https://github.com/mikepenz/release-changelog-builder-action/blob/develop/src/configuration.ts#L32

Beside the 200 pull requests it also maxes out at 90 days back from the current date. (Can also be modified in the settings)
https://github.com/mikepenz/release-changelog-builder-action/blob/develop/src/configuration.ts#L33

Looking at the diffs for rc2 and rc3
https://github.com/vshn/k8up/compare/v0.1.10...v1.0.0-rc2
https://github.com/vshn/k8up/compare/v0.1.10...v1.0.0-rc3
It looks like the first merges were already `2nd of September 2020`. the 90 days would top out at the `13th of October 2020` already though. 
As you already correctly pointed out with the highlighting of the `⚠️ Adjusted 'fromDate' to go max 90 back` log message

----

Side note. 1 thing I tend to do is: have pre releases only have partial release notes, and the final one to have the full release note. 

With a very basic check like
```
ignorePreReleases: ${{ !contains(github.ref, '-') }}
```
(e.g. releases with a `-` won't use that. which fits for all things like -rc01, ... )

**Comment by mikepenz** [comment] 2021-01-11 17:53
Currently debugging this locally. 

I see the following:

```
ℹ️ Comparing vshn/k8up - 'v0.1.10...v1.0.0-rc3'
ℹ️ Found 250 commits from the GitHub API for vshn/k8up
⚠️ Adjusted 'fromDate' to go max 90 back
ℹ️ Fetching PRs between dates 2020-10-13T15:24:24.000Z to 2021-01-11T16:24:24.000Z for vshn/k8up
ℹ️ Retrieved 91 merged PRs for vshn/k8up
ℹ️ Retrieved 250 release commits for vshn/k8up
::endgroup::
::group::📦 Build changelog
ℹ️ Sorted all pull requests ascending: ASC
ℹ️ Used 1 transformers to adjust message
✒️ Wrote messages for 81 pull requests
ℹ️ Ordered all pull requests into 6 categories
✒️ Wrote 81 categorized pull requests down
✒️ Wrote 0 non categorized pull requests down
✒️ Wrote 0 ignored pull requests down
ℹ️ Filled template
```

resulting in:


```
81 changes since v0.1.10
    
    ## 🚀 Features
    
    - Print version number at K8up startup (#161)
    - Limit max concurrent jobs by type (prune, backup, check, etc.) (#164)
    - Add e2e test with bats-detik (#170)
    - Allow default resources to be set on all job types (#175)
    - Add new smart schedules (#186)
    - Add Conditions to the Status information (#204)
    - Add JobSucceeded Condition to Status fields (#218)
    
    ## 🛠️ Minor Changes
    
    - Replacing local playbook.yml with ad-hoc previewer command (#109)
    - Rewrite (#114)
    - Rewrite check executor (#135)
    - Rewrite archive (#139)
    - Rewrite restore (#140)
    - Rewrite prune controller (#133)
    - Add go test & lint gh action (#145)
    - Rework Workflows and Build (#150)
    - Integrate KIND into makefile (#152)
    - Re-add prometheus metrics after Operator SDK migration (#146)
    - Set up issue templates (#158)
    - Ensure legacy and current CRD spec version support (#154)
    - Merge Development to Master (#159)
    - Migrate constants to Koanf (#155)
    - Adjust the exclusivity of the restore and archive job (#174)
    - Ensure repository is always set (#169)
    - Move "Leader-election" CLI flag to Env var (#185)
    - Micro Enhancements (#188)
    - Add .editorconfig (#187)
    - Flatten K8upStatus spec (#191)
    - Add question template to GitHub (#190)
    - Add .dockerignore (#192)
    - Self-documenting Makefile (#189)
    - Disable LEADER_ELECTION by default for make run run_kind (#200)
    - add GitHub Pull Request template (#206)
    - Enable pre release (#222)
    - Setup CodeClimate (#233)
    - Remove Prefix from issues and link questions to GH Discussions (#239)
    - Skip tagging and publishing of floating tags in prereleases (#245)
    - Replace Goreleaser changelog generator with PR-based generator (#248)
    - Replace local registry by loading e2e images directly onto KIND cluster (#250)
    - Display number of changes since which tag in the changelog (#252)
    - Separate e2e tests and KIND from main Makefile (#255)
    - Add junit reporting for e2e tests (#259)
    - Avoid reconciliation loops with predicates (#268)
    - Improve failure handling in GH e2e report workflow (#275)
    - Load the e2e image into KIND in its own make-target (#269)
    
    ## 🐛 Fixes
    
    - Fix s3 restore env vars (#144)
    - Only add ResticPassword if set (#147)
    - Fix global S3 not applied (#157)
    - Fix 'tar: Error opening File' when "make intergration_test" (#199)
    - Fix Null Pointer Dereference (#202)
    - Fix AccountKeySecretRef in Azure backend spec (#211)
    - Grant additional RBAC permissions to K8up (#219)
    - Replace internal schedules when reconciling Schedule CRs (#242)
    - Fix listing of PreBackupPods in foreign namespaces (#240)
    - Ignore existing prebackup deployments (#249)
    - Ensure backwards compatibility of GLOBALSECRETACCESSKEY variable (#258)
    - Pass Scheduler Backend Config to Childresources (#260)
    - Fix Check Job Creation escapade (#266)
    
    ## 📄 Documentation
    
    - Documentation & formatting fixes (#103)
    - Fix minio install in tutorial (#113)
    - Add basic contributing docs, port README (#134)
    - Recover documentation (#160)
    - Docs: fix typo readme (#180)
    - Fixes in backup.adoc (#201)
    - Update K8up Documentation (#205)
    - Update documentation configuration and small docs fixes (#221)
    - Use weekly random schedule in tutorial (#243)
    - Show link to changelog in the docs (#253)
    - Convert architecture from png to svg and include in documentation (#254)
    - Document Kustomize installation instructions (#262)
    - Better distinguish between non-standard and k8up generative schedules (#267)
    
    ## 🔗 Dependency Updates
    
    - Updated vale to latest version (#142)
    - Upgraded antora-preview to latest version (#111)
    - Pin dependency bats to 1.2.1 (#178)
    - Update module onsi/gomega to v1.10.3 (#182)
    - Update module imdario/mergo to v0.3.11 (#171)
    - Update k8s.io/utils commit hash to 67b214c (#162)
    - Update module onsi/gomega to v1.10.4 (#193)
    - Update module prometheus/client_golang to v1.9.0 (#209)
    - Update mikepenz/release-changelog-builder-action action to v1.3.0 (#251)
    - Update mikepenz/release-changelog-builder-action action to v1.3.1 (#261)
    - Update module knadh/koanf to v0.15.0 (#270)
 ```

**Comment by mikepenz** [comment] 2021-01-11 17:54
This seems to be complete and correct. so the question now is why GitHub would have returned an incorrect number or pull request via their API :/

**Comment by ccremer** [comment] 2021-01-11 17:59
Thanks for having a thorough look!
This looks better, but I still don't quite understand how this difference is being created.

> so the question now is why GitHub would have returned an incorrect number or pull request via their API :/

Do you get a reproducible number now? Is it now always 81 listed changes or does that vary?
I wonder whether the API is wonky or the PR retrieval code (async stuff, etc?)

**Comment by mikepenz** [comment] 2021-01-11 18:05
@ccremer rerun it 5 times locally and would always retrieve the same data

91 merged PRs
250 release commits

-----

The code is using the octokit SDK with pagination:
https://github.com/mikepenz/release-changelog-builder-action/blob/develop/src/pullRequests.ts#L75-L130

I wonder if for whatever reason the API delivered the data in a wrong sorted order ending up to bail out early:
https://github.com/mikepenz/release-changelog-builder-action/blob/develop/src/pullRequests.ts#L124-L125

**Comment by ccremer** [comment] 2021-01-11 18:09
Hm, between the rc3 release run and your investigations, I changed the titles of some PRs to be more nicer-looking, but no more than maybe 10. Maybe this caused an update / date change? 
Example this one: https://github.com/vshn/k8up/pull/135

**Comment by ccremer** [comment] 2021-01-11 18:16
> I wonder if for whatever reason the API delivered the data in a wrong sorted order ending up to bail out early:

You might be onto something. I just started a new run and it also gets 91 PRs now: https://github.com/vshn/k8up/runs/1683132005

**Comment by mikepenz** [comment] 2021-01-11 18:17
@ccremer that may describe it. the problem is GitHubs API does not allow us to filter PRs which were merged between 2 tags. that's on the action to resolve. Furthermore it also does not allow to sort the endpoint based on their "merge" date. 

As such the action retrieves a page of pull request sorted by the last updated time. and the action iterates until we either hit the max amount of pull requests or if the first PR in the list (so the newest in relatively to the current list) has a merge date after the from date (or 90 days (max back date relatively) seen respectively))

So I would believe setting the `"max_back_track_time_days": 180` will result in 91 merged pull requests

**Comment by mikepenz** [comment] 2021-01-11 18:44
So as far as I can say right now the problem is a combination of:

- 90 days is too short for this particular release
- the last change, changed due to titles getting modified since
- due to the above (PRs being modified) + 90 days, not all PRs are included / some are missing  

---------

So immediate solution to fix for you: extend the back track time to something longer better meeting your release schedule. 

--------

Things I will consider in the action:
- adjust the paging size to 100 PRs, so it should speed up fetching many PRs and make it less likely for people to run into this problem (if the 90 days are not enough) 
- check if we have a chance to better highlight that if we run into this (that's gonna be a though one though as it may be anticipated -> we don't want to go through all PRs of all times) 
-

**Closed** 2021-01-11 22:02 UTC

**Comment by mikepenz** [comment] 2021-01-11 22:08
releasing an update which will extend the default max backtrack time to 365 days. 
this should be more fitting for projects where releases have more time between each other than 90 days. 

additionally the PR paging size was updated to 100 PRs to speed up data fetching. 

Will release as 1.4.1. Please let me know if there are any other things we can do to improve

**Comment by ccremer** [comment] 2021-01-12 08:17
This is awesome, many thanks! Just updated now, let's see how the next release goes. Should be around in a week or two.
Meanwhile I have copied the changelog that you posted here and pasted into rc3, in case you're wondering why it's now the full changelog.

> Side note. 1 thing I tend to do is: have pre releases only have partial release notes, and the final one to have the full release note.

We'll try that out! In our case "contains -rc" should be a little more robust.

Again, many thanks for quickly responding and coming up with explanations, suggestions and fixes :100:

**Comment by mikepenz** [comment] 2021-01-12 08:25
@ccremer you are welcome. I have rerun it a few times locally and it looked fine in all the cases. So I believe it will be good. Additionally the full release (as long as it's within a year from the last + less than 200 PRs merged :D) should contain all changes. In any case (if you setup the action locally you can for example modify 1 test case in the `releaseNotesBuilder.test.ts` https://github.com/mikepenz/release-changelog-builder-action/blob/develop/__tests__/releaseNotesBuilder.test.ts and have it go against your repo with the tags :) ) 
That's how I was able to quickly re-run the action. 

And nice. great plan. 

Works too. In general I love to have pre releases only have partial changelogs, and the full release to contain the full set. 

You are very welcome! thank you so much for the super detailed report, which was helping significantly to help getting this resolved!
