### ISSUE TITLE
Error: The process '/usr/bin/git' failed with exit code 128

### ISSUE THREAD

**Issue by tomijais** [mikepenz/release-changelog-builder-action#199] opened 2021-02-24 16:01 UTC
So im trying to create my first workflow in order to create a good and automate changelog, but i think im missing in something because i cant stop getting this error.

I want to use as a trigger the push to main, in this case to confirm the merge of the PR, what do u recommend me? This is my error.
![image](https://user-images.githubusercontent.com/29215699/109028118-40dcf700-76a0-11eb-8aec-7d33ab8319a2.png)

And this is the changelog.yml
```
name: changelog

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'package.json'
      - 'CHANGELOG.md'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Release Changelog Builder
        uses: mikepenz/release-changelog-builder-action@v1.5.0
        with:
          fetch-depth: 0 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by mikepenz** [comment] 2021-02-24 16:15
Hi @tomijais 

you will need to checkout the repository within your build, as GitHub actions doesn't do that automatically. 
See an example here: https://github.com/mikepenz/FastAdapter/blob/develop/.github/workflows/ci.yml#L15-L18

The `fetch-depth` comment in the README also references the `checkout` action (so please remove that part from this libraries action) 

You can also see the action being used for example in this build here:
https://github.com/mikepenz/FastAdapter/blob/develop/.github/workflows/ci.yml#L117-L125

**Comment by mikepenz** [comment] 2021-02-24 16:17
If you do not want to checkout the repo for this job you will be required to provide the `toTag` config, as the action won't be able to automatically detect the tag on the current state of the repo:
https://github.com/mikepenz/release-changelog-builder-action/blob/develop/.github/workflows/ci.yml#L35

**Comment by kaermorchen** [comment] 2021-03-02 14:20
Hello. I have the same issue.

![Screenshot_2021-03-02 Build software better, together](https://user-images.githubusercontent.com/11972062/109661748-5c05a600-7b7b-11eb-8139-f2147e6a211d.png)

```
name: Changelog

on:
  pull_request:
    types: [closed]

  push:
    tags:
      - 'v*'
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Build Changelog"
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v1.5.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by mikepenz** [comment] 2021-03-02 14:53
@kaermorchen you'll need to checkout the repo. Please see my comments above:
https://github.com/mikepenz/release-changelog-builder-action/issues/199#issuecomment-785190680
https://github.com/mikepenz/release-changelog-builder-action/issues/199#issuecomment-785191883

**Comment by kaermorchen** [comment] 2021-03-02 16:15
@mikepenz I use action `checkout` (code above)

**Comment by mikepenz** [comment] 2021-03-02 16:17
@kaermorchen does your repo have any tags?

**Comment by cmsj** [comment] 2021-03-03 01:42
@kaermorchen do you have `fetch-depth: 0` in your checkout action? If not you've only checked out a single merge commit, which won't have any tags with it.

**Comment by mikepenz** [comment] 2021-03-03 07:30
Thanks @cmsj. Totally forgot to mention that too. 

----

Usually the action is used for release builds, when the top is also the commit with the tag associated. (E.g. for the tag push trigger)

**Comment by mikepenz** [comment] 2021-03-06 15:47
The problem should be resolved with the above answers. Please let me know if not, closing for the time being

**Closed by mikepenz** 2021-03-06 15:47 UTC

**Comment by lgmorand** [comment] 2021-04-30 07:20
Hello @mikepenz , I have the same issue in a workflow not using the tag trigger

Here is my yaml file

```
    steps:
    - uses: actions/checkout@v2
      with:
          fetch-depth: 100
    - name: "Build Changelog"
      id: build_changelog
      uses: mikepenz/release-changelog-builder-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

The repo has three tags, only one following the semver

Here is the error I get

Run mikepenz/release-changelog-builder-action@v1

```
📘 Reading input values
  /usr/bin/git rev-list --tags --skip=0 --max-count=1
  /usr/bin/git describe --abbrev=0 --tags 
  fatal: No names found, cannot describe anything.
  Error: The process '/usr/bin/git' failed with exit code 128
```

When I run the same commands manually, it finds one tag
```

E:\Repos\test>git rev-list --tags --skip=0 --max-count=1
abe0742fcbe9da4ed0c53a1440a325145fd49919

E:\Repos\test>git describe --abbrev=0 --tags
v1.0.0
```


What could be missing ?

**Comment by mikepenz** [comment] 2021-04-30 07:24
@lgmorand thank you for the report. 

In this specific case it looks to fail retrieving the tag from `git` directly. is this on github runners or a private runner? 
it looks like the local repo (at least in the location the actions are executed) does not have any tags avialable

**Comment by lgmorand** [comment] 2021-04-30 07:54
I'm using GH runner. here is my new test:

```
🔖 Resolve previous tag
  ℹ️ Found 3 (fetching max: 200) tags from the GitHub API for lgmorand/test
  
  Error: 💥 Unable to retrieve previous tag given v1.0.0
```

So it found my 3 tags through API but indeed if I run git tag, it does not find any.
Looks like "GH tags" are not Git tags. I really though there were the same :-/

**Comment by mikepenz** [comment] 2021-04-30 08:00
if you use your own self hosted runner it could be that a too old `git` is installed on the system (that's what I made experience with) 

with the latest official github runners this should not be the case though. 

With the `fetch-depth: 100` the `checkout` action should checkout the tags, unless they are too far in the past? (do you by chance have over 100 commits since the last tag) 


(the error that it can't retrieve a previous tag sounds sufficient for v1.0.0 if no 0.x.y exists)

**Comment by lgmorand** [comment] 2021-04-30 08:09
Thanks for helping <3

The tag is one commit in the past but I found issues on the checkout action with regression regarding the -no-tags parameters. Following the comments, I did a fetch-deptch: 0 and tags are properly retrieved


If you look at this run: https://github.com/lgmorand/test/runs/2473888478?check_suite_focus=true
tags are retrieved but the action does find my tag while it's listed just above.

**Comment by mikepenz** [comment] 2021-04-30 08:16
@lgmorand looked at the run and the tags on the repo. I can indeed not see any tag which would follow `semver` and is before the v1.0.0 tag. 

if you will create a new release v1.0.1 it should properly detect v1.0.0 as the release before that. 

the action works the following way:

- retrieve the current tag (either via the trigger or `git`)
- try to identify the previous tag
  - load tags from github
  - by default use semver to order the tags, and find the previous tag
- retrieve diff between 2 resolved tags 
- get PRs merged within the diff
- build up the changelog

**Comment by mikepenz** [comment] 2021-04-30 08:18
Btw. you can also enable additional logging in github actions: https://docs.github.com/en/actions/managing-workflow-runs/enabling-debug-logging

**Comment by lgmorand** [comment] 2021-04-30 08:23
That's it THANKS. adding a second tag make me go further. now asking for PR because I didn't specify commit mode.

Any reason, it does not work with tags not following semver ? it is because it's more convenient for sorting ? my example is a bad example but I have so cases where tagging help for trigger specific stuff and those tags don't follow semver

**Comment by mikepenz** [comment] 2021-04-30 08:32
So currently the action offers 2 different modes. 

`semver` -> this would be the most accurate approach as semver is very precise in order 

alternative the action offers a `sort` mode (will use sorting to order, please be aware that if no consistent pattern is used like date or so, this may order wrong) 

This was recently highlighted here: https://github.com/mikepenz/release-changelog-builder-action/issues/276#issuecomment-825438111

And is also noted in the README


tag_resolver.method | Defines the method to use. Current options are: semver, sort. Default: semver
-- | --

**Comment by mikepenz** [comment] 2021-04-30 08:33
You can find the logic doing this here: https://github.com/mikepenz/release-changelog-builder-action/blob/develop/src/tags.ts#L103-L107

**Comment by lgmorand** [comment] 2021-04-30 09:34
Sorry for not reading the readme carefully. thanks for the quick help
