### ISSUE TITLE
Example doesn't seem to generate notes

### ISSUE THREAD

**Issue by DevJackSmith** [mikepenz/release-changelog-builder-action#1061] opened 2023-03-25 00:17 UTC
I tried the example in readme, but instead of release step i used echo, just to see the notes.
It finds PRs, it finds commits, it finds files changed, but it doesn't generate any release notes as far as i can tell.
Example workflow: https://github.com/m-h-c-t/mh-helper-extension/actions/runs/4516363137/workflow
Output of that run: https://github.com/m-h-c-t/mh-helper-extension/actions/runs/4516363137/jobs/7954600378
it says it's not failed. But when i try to echo the notes, it gives blank.

**Comment by mikepenz** [comment] 2023-03-25 18:29
Further down in the README you will find a full sample herE: https://github.com/mikepenz/release-changelog-builder-action#full-sample-%EF%B8%8F

the action requires information about fromTag and toTag which is normally retrieved from the `tag` action trigger. 

If that's not the case, it can alternative retrieve it from `git` but for that a `checkout` step would be required prior. 

Or you can provide `toTag` and `fromTag` manually. 

The action in use here: https://github.com/mikepenz/release-changelog-builder-action/blob/develop/.github/workflows/ci.yml#L132-L153

**Comment by alexanderjpowell** [comment] 2023-03-28 09:14
I'm using `fromTag` and `toTag` as parameters and the actions runs successfully but I also observe the same behavior where the `outputs.changeLog` is empty.  Are you saying this is a known issue?

**Comment by mikepenz** [comment] 2023-03-28 10:12
Do you have the link to the execution available where you did provide `fromTag` and `toTag`?

**Comment by alexanderjpowell** [comment] 2023-03-29 03:15
It's in a private repo.  I can try to make a public dummy repo with an example.

**Comment by alexanderjpowell** [comment] 2023-03-29 07:10
The PRs do follow the labels you described.  What would be the best way for the changeLog output to just include all commits in a list, regardless of their label?

I setup and example repo and ran the action here: https://github.com/alexanderjpowell/release-notes-test/actions/runs/4551167361/jobs/8024928251

Note that in this example I didn't actually merge PRs but kept committing and pushing new tags to master, not sure if that matters.  But in the outputted changeLog it just prints `"- no changes"`
Look at the step Print Changelog step (ignore the failing create release step).

Thanks 🙏

**Comment by alexanderjpowell** [comment] 2023-03-29 07:22
Thanks for the quick responses!  Ok that makes sense, in the private repo they are PRs but let me try to reproduce in the public one first.

**Comment by mikepenz** [comment] 2023-03-29 07:38
@alexanderjpowell in your private one, have a look into the action output, as shown in the screenshot above. It may have some good pointers for you. 

E.g. check:
- does it use the correct range (e.g. the from and toTag you expect)
- does it find PRs
- did it identify the expected merged PRs

**Comment by alexanderjpowell** [comment] 2023-03-29 07:47
Yes, everything seems to work fine in the action output, it gets the fromTag and toTag range correct and dates and everything appear fine.  The only issue is changeLog is empty from what I can see.  

I merged some PRs in my dummy repo and reran the job: https://github.com/alexanderjpowell/release-notes-test/actions/runs/4551480787/jobs/8025595112

I still see empty changelog though.  Do you think it's because it's seeing the PRs as uncategorized?  Currently I'm using the default configuration.  

![Uploading Screenshot 2023-03-29 at 2.45.34 PM.png…]()

**Comment by mikepenz** [comment] 2023-03-29 07:49
Correct. The default template does not list uncategorized. 

<img width="696" alt="Screenshot 2023-03-29 at 09 48 39" src="https://user-images.githubusercontent.com/1476232/228463700-953fa41b-0b16-4cb4-a159-84d8296035bf.png">

Try providing a config (you can do so directly via the yml). An example:
https://github.com/mikepenz/release-changelog-builder-action/blob/develop/.github/workflows/ci.yml#L47-L72

**Comment by alexanderjpowell** [comment] 2023-03-29 07:55
Ah, ok it's working now in the dummy repo so yes, it seems it's an issue with all the PRs being marked as non categorized. Will fix in the the private repo. 

Thanks so much for the support!

**Comment by mikepenz** [comment] 2023-03-29 08:03
You are welcome

**Closed** 2023-04-08 09:10 UTC
