### ISSUE TITLE
Is there any way to get unreleased PR's?

### ISSUE THREAD

**Issue by lucasgismondi-bitbuy** [mikepenz/release-changelog-builder-action#725] opened 2022-04-05 19:07 UTC
Is it possible to get all PR's from the latest release tag to now?

I tried to use the commit sha from the latest release to the current commit sha but with no luck. Is there any way this can be achieved?

Thank you!

**Comment by mikepenz** [comment] 2022-04-05 20:32
Hi @lucasgismondi-bitbuy 

Thank you very much for the ticket. 

Currently this action is focusing around merged PRs. 

Could you may outline a bit on your usecase to understand better on this ask?

**Comment by lucasgismondi-bitbuy** [comment] 2022-04-05 20:48
Hey @mikepenz, thanks for the reply.

Within our changelog we are looking to include PR's that are "unreleased" so that our QA and other internal teams can know exactly what is coming up and what has already been released to production

**Comment by mikepenz** [comment] 2022-04-05 20:58
That's an interesting usecase. 

You outline the `toTag` to have no bound, but given the note you'd still like to have those in a `unreleased` section. would those be meant to follow a similar categorisation, or could it be a plain `unreleased` section with everything listed? Filtered by some label? 

It's an interesting feature proposal, and I believe it could add further value to the action.

**Comment by lucasgismondi-bitbuy** [comment] 2022-04-06 13:29
Yes, I would expect it to follow a similar categorization. If it can get a list of PR's that are "unreleased" then it should be able to read the labels on those PR's and sort them accordingly. I'm not sure if that is actually possible though on the actions side but that is what I would expect. If it's just easier to have a plain `unreleased` section with everything listed, that is still a viable solution.

Yeah, I think it's super interesting as well. It can help make the changelog the single source of truth instead of relying on other ticket management tools that require more manual work to keep things organized.

**Comment by mikepenz** [comment] 2022-04-08 08:53
@lucasgismondi-bitbuy if you could please have a look at the following PR and maybe see if it matches your requirements: \
- https://github.com/mikepenz/release-changelog-builder-action/pull/726
(at the time of writing docs are not yet updated, but I hope the testcases added can be a good starting point)

**Comment by mikepenz** [comment] 2022-04-11 15:18
@lucasgismondi-bitbuy as before those should be included if you use the latest commit on the branch those were merged into up until the tag which you want to use as `fromTag`.

**Comment by mikepenz** [comment] 2022-04-11 16:25
<img width="1154" alt="Screenshot 2022-04-11 at 18 23 24" src="https://user-images.githubusercontent.com/1476232/162786189-9f9912f6-e240-4bfd-8cca-a6b4ed93aa93.png">

In a strongly simplified fashion the following should outline your usecase. 

<img width="768" alt="Screenshot 2022-04-11 at 18 24 33" src="https://user-images.githubusercontent.com/1476232/162786344-e1ac51ff-2f01-430d-a934-b793136d7f14.png">

If you look at the config it refers the hash instead the tag. 
and 1 open PR. 

using a special tag `--rcba-open` to add additional flexibility when configuring the sections you may want.

**Comment by lucasgismondi-bitbuy** [comment] 2022-04-11 18:07
So my workflow step looks like this at the moment: 

```
- name: Build Changelog
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v1
        with:
          fromTag: "3.77.0"
          toTag: "${{ github.sha }}"
          configuration: "changelog_config.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

I also tried referencing an existing hash manually and I also tried using "v3.77.0" for the fromTag but I'm getting this: 
<img width="619" alt="image" src="https://user-images.githubusercontent.com/97917022/162802133-0e91e54e-d365-4d3a-bbc6-3888caf35a14.png">

Any ideas as to why this may be failing?

**Comment by mikepenz** [comment] 2022-04-11 19:25
Could it be that the TOKEN is invalid? 

Also it looks you are using v1 while we are already at v2.9.0 and the specific branch created for you with the new feature would have the SHA-1 (df9a35580f26de56d97c703c0505929f31b4693b - which you can use as version spec)

**Comment by lucasgismondi-bitbuy** [comment] 2022-04-12 14:20
The token is definitely valid since it works very well between two releases. I tried using 2.9.0 and the new branch sha but neither of those worked. But before this PR was created, was it expected that you can get merged PR's between a release tag and any commit sha that came after that? If so, I'm not sure if the PR you linked is needed since we don't need to reference open PR's

**Comment by mikepenz** [comment] 2022-04-12 14:42
You can enable debug logging which should give you additional details on the reason for the failure:
https://docs.github.com/en/github-ae@latest/actions/monitoring-and-troubleshooting-workflows/enabling-debug-logging#enabling-step-debug-logging
When you verify the `sha` used looks correct?
Other than that usual common causes for something like this may be wrong scope/permissions of the token.

Yes it is and was possible before this PR to retrieve merged PRs between 2 git hashes. 
So that's great news of things already being available as needed prior to the PR. 

----

I can assist to setup local debugging if you wish to iterate faster, or guide you in this direction.

**Comment by lucasgismondi-bitbuy** [comment] 2022-04-12 17:55
Yes, the sha used is correct in both scenarios (using `"${{ github.sha }}"` or inserting manually)

Thank you very much for all the support you've provided. As of right now this action works very well for automating our changelog on release. I'm going to have to come back to this and iterate on this in the future.

**Comment by mikepenz** [comment] 2022-04-12 17:57
@lucasgismondi-bitbuy thank you. So you found the cause for the `HttpError: Not found` issue?

**Comment by lucasgismondi-bitbuy** [comment] 2022-04-12 18:00
No this issue hasn't been resolved yet. I will come back to this probably within a few weeks

**Comment by mikepenz** [comment] 2022-05-13 14:03
Closing this issue due to inactivity. Please re-open with additional information so we can investigate further and resolve it :) 

Given the error it looks that it is most likely a permission issue.

**Closed by mikepenz** 2022-05-13 14:03 UTC

**Comment by mikepenz** [comment] 2023-01-02 09:35
@dtcMLOps  You can enable to `includeOpen` PRs by doing: 
<img width="669" alt="Screenshot 2023-01-02 at 10 31 57" src="https://user-images.githubusercontent.com/1476232/210214085-4cc1dd25-8280-4305-b30e-c04beb257edd.png">

Which will result in open PRs being included for the changelog generation. (please note that they are included in the general set of PRs and are to be categorized with the category)

**Comment by mikepenz** [comment] 2023-01-03 07:45
@dtcMLOps I'll need to think of some additional APIs to make the category more flexible

**Comment by lucasgismondi-bitbuy** [comment] 2023-01-08 23:13
Awesome, thanks @dtcMLOps !
