### ISSUE TITLE
New feature category rules might not be working

### ISSUE THREAD

**Issue by codebydant** [mikepenz/release-changelog-builder-action#999] opened 2023-01-06 11:26 UTC
Hi @mikepenz,

Thanks for this wonderful tool :rocket: 

I have been trying to set the new feature **categories rules** to create the "Unreleased" section in the changelog and it works. I mean, I am getting the open PRs in a new section but without the categorization. I have used the example in the docs to configure this, but I am not sure I am missing something.

![Screenshot from 2023-01-06 06-22-36](https://user-images.githubusercontent.com/115469901/211002939-d3a93057-b918-4064-a5d1-4ac1e65b07fe.png)

## configrc
```yml
configurationJson: |
      {
        "categories": [
          {
            "title": "## 🚀 Features",
            "labels": [
              "feat(${{ inputs.scope }})"
            ],
            "rules": [
              {
                "pattern": "open",
                "on_property": "status",
                "flags": "gu"
              }
            ]
          },
          {
            "title": "## 🐛 Fixes",
            "labels": [
              "fix(${{ inputs.scope }})"
            ],
            "rules": [
              {
                "pattern": "open",
                "on_property": "status",
                "flags": "gu"
              }
            ]
          },
          {
            "title": "## 🧪 Tests",
            "labels": [
              "test(${{ inputs.scope }})"
            ],
            "exhaustive": true,
            "rules": [
              {
                "pattern": "open",
                "on_property": "status",
                "flags": "gu"
              }
            ]
          }
        ],              
        "sort": {
          "order": "ASC",
          "on_property": "mergedAt"
        },
        "template": "All notable changes to this project will be documented in this file.\n\n## Changes #{{RELEASE_DIFF}}\n\n#{{CHANGELOG}}## 💬 Other\n\n#{{UNCATEGORIZED}}\n## 📖 Unreleased\n#{{OPEN}}",
        "pr_template": "- ##{{NUMBER}} #{{TITLE}} @#{{AUTHOR}}",
        "label_extractor": [
          {
            "pattern": ".*(feat\\(${{ inputs.scope }}\\)).*",
            "target": "$1",
            "on_property": "title"
          },
          {
            "pattern": ".*(fix\\(${{ inputs.scope }}\\)).*",
            "target": "$1",
            "on_property": "title"
          },
          {
            "pattern": ".*(test\\(${{ inputs.scope }}\\)).*",
            "target": "$1",
            "on_property": "title"
          }
        ]
      }
```

Related to #725

**Comment by mikepenz** [comment] 2023-01-06 11:54
@dtcMLOps thank you for the report. 

Yes that works as intended. The action allows for elements to be matched multiple times. 

If you do not want to have open PRs not included in section for only `merged` PRs. Then you can add a rule there which only matches `PRs` which are `merged`. It's worth noting that this will require the `exhaustive` flag - as all conditions have to apply (e.g. an `and` instead of an `or`) 

Beside that, I forgot to mention that the action also injects a `special` label for the status. Which is automatically added to all PRs: https://github.com/mikepenz/release-changelog-builder-action/blob/6dc744480052b90c7b1e195434ca4f11c96930fc/src/pullRequests.ts#L247
You can also use this `special` label to exclude them. https://github.com/mikepenz/release-changelog-builder-action/blob/6dc744480052b90c7b1e195434ca4f11c96930fc/configs_test/configuration_excluding_open.json#L2-L13 

Theoretically you can solve the full requirement with that too (apologies for not mentioning it earlier)

**Comment by mikepenz** [comment] 2023-01-06 12:31
Hmmm that's interesting. the fact that it is added to `unreleased` should prevent it to be `UNCATEGORIZED` 
(e.g. a PR being in any category, prevents it from being uncategorized) 

How's other defined in your case?

**Comment by mikepenz** [comment] 2023-01-06 12:39
@dtcMLOps that explains it. 
If you make the unreleased a real category and uncategorized too, then things should match your expectation.

Otherwise uncategorized can't know about the open ones. 

The open category could be as simple as:
```
     { 
         "title": "Open", 
         "labels": ["--rcba-open"]
     } 
```

The uncategorized category could be as simple as:

```
{
            "title": "## 📦 Uncategorized",
            "labels": []
        }
```

**Closed as completed** 2023-01-06 13:49 UTC
