### ISSUE TITLE
No changes for pull request

### ISSUE THREAD

**Issue by ThePieMonster** [mikepenz/release-changelog-builder-action#704] opened 2022-03-09 20:18 UTC
I wanted to create a separate issue where I am seeing "no changes" for the pull request. Using the default labels for issues and pull requests in GitHub, the current pull request that is synchronizing (thus generating the build) is labeled with "enhancement" currently. I would expect there to be some output instead of "no changes". 

    - name: Get Changelog
      uses: mikepenz/release-changelog-builder-action@v2
      id: Changelog
      with:
          configuration: ".github/configs/configuration.json"
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            
    - name: Output Changelog
      run : |
        echo "Output Changelog"
        echo "${{ steps.Changelog.outputs.changelog }}"

![image](https://user-images.githubusercontent.com/11359134/157527014-dd2878ad-794d-41a8-8939-7861bbf075c0.png)
![image](https://user-images.githubusercontent.com/11359134/157527080-85572c2e-1591-4782-95aa-7fd977110308.png)

```
{
    "categories": [
        {
            "title": "## 🚀 Features",
            "labels": ["feature", "enhancement"]
        },
        {
            "title": "## 🐛 Fixes",
            "labels": ["fix", "bug"]
        },
        {
            "title": "## 🧪 Tests",
            "labels": ["test"]
        },
		{
            "title": "## 💬 Other",
            "labels": ["other", "documentation"]
        },
        {
            "title": "## 📦 Dependencies",
            "labels": ["dependencies"]
        }
    ],
    "sort": "ASC",
    "template": "${{CHANGELOG}}",
    "pr_template": "- ${{TITLE}}\n   - PR: #${{NUMBER}}",
    "empty_template": "- no changes",
    "max_pull_requests": 1000,
    "max_back_track_time_days": 1000
}
```

**Comment by mikepenz** [comment] 2022-03-09 21:41
How many PRs did you merge between 2.0.5 and 2.0.4?

According to the log there is 1 non categorised PR (e.g. it did not have a label matching the categories you provided)


The default template will only output PRs which got matched. 


-------

A hopefully helpful note on the side. You can set-up the action locally on your computer, and run it via it's test cases, so you can quicker iterate on your configuration and setup, and potentially even debug. 

I did go into some detail on this for example here: https://github.com/mikepenz/release-changelog-builder-action/issues/483#issuecomment-919055917

**Comment by ThePieMonster** [comment] 2022-03-10 06:02
@mikepenz 
According the config that I posted above I have the label "enhancement" setup in the features section and according to the screenshot below the PR has that label. Is there something I am missing here?
![image](https://user-images.githubusercontent.com/11359134/157599144-9fb3e052-ffa8-4488-9059-fb8c8c2587f3.png)

Also this is the only PR (its the 2.0.5 PR, tag was created as part of the build process). Each merged PR is essentially creating a release, thus each PR will be making a new tag during the build process.

**Comment by mikepenz** [comment] 2022-03-10 07:01
Based on your screenshot it looks the PR is not yet merged? Was the PR merged during the build process?

**Comment by ThePieMonster** [comment] 2022-03-10 23:18
> Based on your screenshot it looks the PR is not yet merged? Was the PR merged prior running the build process (and thus the changelog action)?

@mikepenz 
The PR has been created, multiple commits have been added (each triggering a build that must pass), and the PR is still open (has not yet been merged). 

Even though the PR has not yet been merged, I would expect to see the ongoing change log.

**Comment by mikepenz** [comment] 2022-03-11 07:56
@ThePieMonster this is the cause for the issue. This action works only on merged PRs:
- https://github.com/mikepenz/release-changelog-builder-action/blob/22312e9533d6fcbb7b4b7ec241cf37469a861f1b/src/pullRequests.ts#L51

**Comment by ThePieMonster** [comment] 2022-03-11 19:18
> @ThePieMonster this is the cause for the issue. This action works only on merged PRs:
> 
> * https://github.com/mikepenz/release-changelog-builder-action/blob/22312e9533d6fcbb7b4b7ec241cf37469a861f1b/src/pullRequests.ts#L51

@mikepenz The below is the output from a PR that is merged (closed) now. As you can see I have a few outputs at the top of the workflow that output the "github.action" states. Feel free to look at my most recent repo in my profile and you can see the workflow for yourself.

![image](https://user-images.githubusercontent.com/11359134/157936207-ec16532a-01ca-491f-b916-264a39922447.png)
![image](https://user-images.githubusercontent.com/11359134/157936319-dd011cd2-46a0-40f6-98b4-b2313a180167.png)

**Comment by mikepenz** [comment] 2022-03-14 19:30
I suppose you are referring to this repo? https://github.com/ThePieMonster/HideMockLocation

**Comment by ThePieMonster** [comment] 2022-03-14 22:22
> I suppose you are referring to this repo? https://github.com/ThePieMonster/HideMockLocation

@mikepenz 
You can view the workflow file here
https://github.com/ThePieMonster/HideMockLocation/blob/main/.github/workflows/gradle-build.yml

**Comment by mikepenz** [comment] 2022-03-15 07:41
Looking at the diff for the release 2.0.4 vs 2.0.5 it looks only the `update gradle build` was merged: https://github.com/ThePieMonster/HideMockLocation/compare/2.0.4...2.0.5

And that one did not have a label https://github.com/ThePieMonster/HideMockLocation/pull/19, thus being moved in the non categorised section.

**Comment by mikepenz** [comment] 2022-03-15 07:50
This can be reproduced / debugged by using: https://github.com/mikepenz/release-changelog-builder-action/commit/0f8c9a42c2bf7746513841b7690c79206e43031b

With the project checked out locally a token configured and running `npm test -- hidemockloc.test.ts`

**Comment by ThePieMonster** [comment] 2022-03-15 17:20
@mikepenz 
Committed the file to the working branch below so you could review it.
https://github.com/ThePieMonster/HideMockLocation/tree/ThePieMonster-UI/.github

I am however getting an error when I try to run the test. See the below:

```
$ npm test -- .github/configs_test/changelog.test.ts
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path C:\GIT\HideMockLocation/package.json
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, open 'C:\GIT\HideMockLocation\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

```

**Comment by mikepenz** [comment] 2022-03-15 18:34
@ThePieMonster oh you would not need to commit this file in your repo, but check out the source of this action.

Then go into the checked out source and use `npm install` and then to use `npm` locally to run the tests. 
I have no windows system so I can't check if there would be any other requirements. for executing it.

**Comment by ThePieMonster** [comment] 2022-03-16 05:14
@mikepenz Gotcha.

So it seems like an error is shown.
```
$ npm test -- changelog.test.ts

> release-changelog-builder-action@v1.0.0 test
> jest "changelog.test.ts"

::debug::configurationPath = 'C:\GIT\release-changelog-builder-action\configs_test\configuration_commits_emoji.json'
ℹ️ Configuration successfully loaded.

::set-output name=owner::ThePieMonster
::debug::Resolved 'owner' as ThePieMonster

::set-output name=repo::HideMockLocation
::debug::Resolved 'repo' as HideMockLocation
::endgroup::
::group::� Resolve tags
ℹ️ Found 7 (fetching max: 200) tags from the GitHub API for ThePieMonster/HideMockLocation

::set-output name=toTag::2.0.6
::debug::Resolved 'toTag' as 2.0.6

::set-output name=fromTag::2.0.5
::debug::fromTag resolved via previousTag as: 2.0.5
::endgroup::
::group::� Load pull requests
ℹ️ Comparing ThePieMonster/HideMockLocation - '2.0.5...2.0.6'
ℹ️ Found 34 commits from the GitHub API for ThePieMonster/HideMockLocation
ℹ️ Fetching PRs between dates 2022-03-09T20:05:31.000Z to 2022-03-16T04:58:31.000Z for ThePieMonster/HideMockLocation
ℹ️ Retrieved 20 merged PRs for ThePieMonster/HideMockLocation
ℹ️ Retrieved 34 release commits for ThePieMonster/HideMockLocation

::set-output name=pull_requests::20
::endgroup::
::group::� Build changelog
ℹ️ Sorted all pull requests ascending: ASC
ℹ️ Used 1 transformers to adjust message
✒️ Wrote messages for 1 pull requests
ℹ️ Ordered all pull requests into 5 categories
✒️ Wrote 0 categorized pull requests down

::set-output name=categorized_prs::0
✒️ Wrote 1 non categorized pull requests down

::set-output name=uncategorized_prs::1
✒️ Wrote 0 ignored pull requests down
ℹ️ Filled template
::endgroup::
  console.log
    - no changes

      at __tests__/changelog.test.ts:26:13

 FAIL  __tests__/changelog.test.ts
  × Verify commit based changelog, with emoji categorisation (1515 ms)

  ● Verify commit based changelog, with emoji categorisation

    expect(received).toStrictEqual(expected) // deep equality

    Expected: ""
    Received: "- no changes"

      25 |     const changeLog = await releaseNotesBuilder.build()
      26 |     console.log(changeLog)
    > 27 |     expect(changeLog).toStrictEqual(
         |                       ^
      28 |         ``
      29 |     )
      30 | })

      at __tests__/changelog.test.ts:27:23
      at fulfilled (__tests__/changelog.test.ts:5:58)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        3.151 s
Ran all test suites matching /changelog.test.ts/i.
```

I have a new PR that is waiting to be merged in my repo. You can see this time around that the prior PR (2.0.5) is showing. However, 2.0.5 was released and the current version is 2.0.6 now, and that PR is not shown here. Seems like everything is a version behind for your changelog.
![image](https://user-images.githubusercontent.com/11359134/158521051-35e568c2-b9d2-433c-9591-53eab0292883.png)

**Comment by mikepenz** [comment] 2022-03-16 07:39
Which matches what was mentioned above. Looking at the diff only looks to not contain the changes you expected in v2.0.5: 
https://github.com/ThePieMonster/HideMockLocation/compare/2.0.4...2.0.5


Comparing 2.0.5 with 2.0.6 shows that it contains the merge of PR `#20` 

Given that the action works as expected, and the tags just seem to be in (possibly?) the wrong places

**Comment by ThePieMonster** [comment] 2022-03-17 03:42
@mikepenz Starting to understand why this seems to be "delayed". Since the Changelog action is running in a PR that is "being currently merged" the current PR is not considered completed, thus it will not show up in the changelog.

Seems like I would have to make another GitHub Workflow that kicks off a job with the Changelog and Release Actions when a PR is completed, correct?

**Comment by mikepenz** [comment] 2022-03-17 07:37
@ThePieMonster more specific. the tag is placed at a position where the PR was not merged, but only the changes are there.

So if you can ensure the `tag` is placed after the merge occurred, the action will also detect as the PR being merged. 

You could possibly change the release workflow to be executed for changes on your main branch (wherever the PRs are merged to)

**Comment by ThePieMonster** [comment] 2022-03-17 22:37
@mikepenz I ended up placing the "create tag" step after the merge completed step. There is this check `if: github.event.pull_request.merged == true` that needs to pass before a tag and release can get created now.

Everything looks like it should now, thanks for sticking it out with me!

![image](https://user-images.githubusercontent.com/11359134/158905268-ee374678-5ef5-4fac-ab2b-1b617668a29f.png)
![image](https://user-images.githubusercontent.com/11359134/158905281-629786d5-909d-4418-848c-ebd60b9d38a0.png)

**Comment by mikepenz** [comment] 2022-03-18 07:24
Glad you were able to solve it.

**Closed by mikepenz** 2022-03-18 07:24 UTC
